export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST';
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS';
export const QUIZ_LIST_FAIL = 'QUIZ_LIST_FAIL';

export const QUIZ_DETAILS_REQUEST = 'QUIZ_DETAILS_REQUEST';
export const QUIZ_DETAILS_SUCCESS = 'QUIZ_DETAILS_SUCCESS';
export const QUIZ_DETAILS_FAIL = 'QUIZ_DETAILS_FAIL';

export const QUIZ_SAVE_REQUEST = 'QUIZ_SAVE_REQUEST';
export const QUIZ_SAVE_SUCCESS = 'QUIZ_SAVE_SUCCESS';
export const QUIZ_SAVE_FAIL = 'QUIZ_SAVE_FAIL';
